//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymTracker
    {
        public int ID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string BodyPart { get; set; }
        public string Exercise { get; set; }
        public string Sets { get; set; }
        public string Reps { get; set; }
        public string Weights { get; set; }
    }
}
