//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUploader.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GymTracker
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string BodyPart { get; set; }
        public string Exercise { get; set; }
        public Nullable<short> Sets { get; set; }
        public Nullable<short> Reps { get; set; }
    }
}
